module.exports = {
  draftBox: 'Draft box',
  editedAt: 'Edited ',
  schedule: 'Progress: ',
  cover: 'Cover',
  detail: 'Details',
  partner: 'Partner',
  link: 'Share',
  noProgress: 'No progress yet',
  noData: 'No more data',
  ecoPlus: 'ECO+',
  notYet: 'Unnamed ',
  null: 'Null',
  project: 'Project',
  hasDraft: 'Suggest a product to ',
  product: 'Showroom',
  realProduct: 'Physical',
  digitalProduct: 'Digital',
  nftProduct: 'NFT product',
  check: 'Confirm',
  unavailable: 'Draft data no longer available',
  blog: 'Posts',
  product: 'Showroom',
  title: 'Title',
  content: 'Content',
  coverSetter: 'Cover settings',
  groupDetails: 'Contact Card',
  Thedraftboxwillalwaysbesavedforyou: 'Save your most creative ideas ',
  Themostcreativeinspiration: 'Themostcreativeinspiration',
  Draftcontent: 'Drafts = Data = Appreciating Assets',
  Selected: 'Selected',
  record: 'Record',
  callOfAction: 'Calls to Action',
  videomeeting: 'Voice/Video Meetings',
  valueGifts: 'Value Gifts',
}
